name: Compilar TWRP a3core

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP
    runs-on: ubuntu-22.04 
    
    steps:
    - name: Limpiar espacio en disco
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: false

    - name: Configurar entorno
      uses: actions/checkout@v4

    - name: Configurar Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5 libncurses5-dev libssl-dev x11proto-core-dev libx11-dev libgl1-mesa-dev g++-multilib libxml2-utils xsltproc unzip python2 rsync
        
        # Engañamos al PATH para que 'python' abra Python 2
        mkdir -p $HOME/bin
        ln -s /usr/bin/python2 $HOME/bin/python
        echo "$HOME/bin" >> $GITHUB_PATH
        
    - name: Configurar repo y sincronizar TWRP 11
      run: |
        sudo curl -L https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+rx /usr/local/bin/repo
        
        mkdir ~/twrp
        cd ~/twrp
        
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # Cambiado a manifest_twrp_aosp (Recomendado para TWRP 11)
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clonar Árbol del Dispositivo (a3core)
      run: |
        cd ~/twrp
        # Actualizado para usar tu repositorio (elmendezz) en lugar del original
        git clone https://github.com/elmendezz/android_device_samsung_a3core device/samsung/a3core

    - name: Compilar Recovery
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        
        # CORRECCIÓN: El target debe ser twrp_a3core-eng (o omni_a3core-eng), no pettyl
        lunch twrp_a3core-eng
        make recoveryimage -j$(nproc --all)

    - name: Subir Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-a3core
        path: ~/twrp/out/target/product/a3core/recovery.img
